---
name: Tie-Handle-ToMemory
version: 0.12
author:
  - David A Golden <dagolden@cpan.org>
abstract: Print to or read from a scalar in memory
license: perl
requires:
  perl: 5.004
build_requires:
  Test::Exception: 0.2
  Test::More: 0.47
provides:
  Tie::Handle::ToMemory:
    file: lib/Tie/Handle/ToMemory.pm
    version: 0.12
generated_by: Module::Build version 0.2701
